# Copyright 2021 Alex Litvinov
# See LICENSE file for licensing details.

options:
  debug:
    default: false
    description: Enable DEBUG level logging
    type: boolean

  external_hostname:
    default: nats.juju
    description: External hostname to access NATS
    type: string

  nats_version:
    default: 2.1.7
    description: External hostname to access NATS
    type: string

  client_port:
    type: int
    default: 4222
    description: port for clients

  monitor_port:
    type: int
    default: 8222
    description: port for http monitoring

  cluster_port:
    type: int
    default: 6222
    description: port for nats clustering

